# DestinationRule: giới hạn connection pool + bật outlier detection
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: backline-dr
  namespace: circuit-breaker
spec:
  host: backline.circuit-breaker.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 50
      http:
        http1MaxPendingRequests: 100
        maxRequestsPerConnection: 100
    outlierDetection:
      consecutive5xxErrors: 5          
      interval: 5s              
      baseEjectionTime: 30s     
      maxEjectionPercent: 50    
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: backline-vs
  namespace: circuit-breaker
spec:
  hosts:
  - backline.circuit-breaker.svc.cluster.local
  http:
  - route:
    - destination:
        host: backline.circuit-breaker.svc.cluster.local
        port:
          number: 8000
      weight: 100
    timeout: 2s
    retries:
      attempts: 2
      perTryTimeout: 1s